image: barichello/godot-ci:4.3

variables:
  PROJECT_NAME: gmj-kit
  ITCH_NAME: alvarber

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - export
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  script:
    - godot --headless --verbose --editor --quit

web:
  stage: export
  script:
    - mkdir -v -p build
    - godot --headless --verbose --export-release "web" "build/index.html"
  artifacts:
    name: $PROJECT_NAME-$CI_JOB_NAME
    paths:
      - build

itchio:
  stage: deploy
  script:
    - zip build.zip build/*
    - butler push build.zip $ITCH_NAME/$PROJECT_NAME:html
  dependencies:
    - web