image: barichello/godot-ci:4.3

variables:
  PROJECT_NAME: ggj25
  ITCH_NAME: alvarber

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - everything

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  
pages:
  stage: everything
  script:
    - mkdir -v -p build
    - godot --headless --verbose --path project --export-release "web" "../build/index.html"
    - zip build.zip build/*
    # - butler push build.zip $ITCH_NAME/$PROJECT_NAME:html
    - mv build public
  pages: true
  artifacts:
    paths:
      - public