version: '3'

env:
  ITCH: alvarber/whatever

dotenv:
  - .envrc

tasks:
  upload:
    deps:
      - zip
    cmds:
      - >
        "$BUTLER" push out.zip $ITCH:html
    sources:
      - out.zip
  zip:
    deps:
      - export
    cmds:
      - zip out.zip out/*
    sources:
      - out/*
    generates:
      - out.zip
  export:
    cmds:
      - $GODOT --no-window --path . --export HTML5 out/index.html
    sources:
      - '*'
      - exclude: out/*
      - exclude: out.zip
      - exclude: Taskfile.yaml
      - exclude: .gitignore
      - exclude: .envrc
      - exclude: .import/*
    generates:
      - out/*
  clear:
    cmds:
      - rm -rf out/*