version: '3'

env:
  ITCH: alvarber/ggj25

dotenv:
  - .envrc

tasks:
  upload:
    deps:
      - zip
    cmds:
      - >
        "$BUTLER" push build.zip $ITCH:html
    sources:
      - build.zip
  zip:
    deps:
      - export
    cmds:
      - zip build.zip build/*
    sources:
      - build/*
    generates:
      - build.zip
  export:
    cmds:
      - mkdir -p build
      - $GODOT --headless --path project --export-release web ../build/index.html
    sources:
      - project/**/*
      - except: project/**/.DS_Store
      - except: project/.godot
    generates:
      - build/*
  clear:
    cmds:
      - rm -rf build/*