version: '3'

env:
  ITCH: alvarber/whatever

dotenv:
  - .envrc

tasks:
  upload:
    deps:
      - zip
    cmds:
      - >
        "$BUTLER" push build.zip $ITCH:html
    sources:
      - build.zip
  zip:
    deps:
      - export
    cmds:
      - zip build.zip build/*
    sources:
      - build/*
    generates:
      - build.zip
  export:
    cmds:
      - mkdir -p build
      - $GODOT --headless --export-release web build/index.html
    sources:
      - '*'
      - exclude: build/*
      - exclude: build.zip
      - exclude: Taskfile.yaml
      - exclude: .gitignore
      - exclude: .gitattributes
      - exclude: .envrc
      - exclude: .import/*
    generates:
      - build/*
  clear:
    cmds:
      - rm -rf build/*